#!/bin/sh

# See how we were called.
case "$1" in
  start|"")
    echo -e "\n   Starting daemongps..."
    /usr/local/sbin/daemongps > /dev/null &
    ;;

  stop)
    echo -e "\n   Sorry, this is not supported. Do it manually!\n"
    ;;

  restart)
        $0 stop
        $0 start
        ;;

  status)
    echo -e "\n   Sorry, this is not supported. Do it manually!\n"
        ;;

  *)
        echo "Usage: daemongps {start}"
        exit 1
esac

exit 0


